import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './components/layout/Navbar'
import Footer from './components/layout/Footer'
// import "tw-elements/dist/css/tw-elements.min.css";
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Shopify Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      <body className={inter.className}>{children}</body>
      <Footer />
    </html>
  )
}
